export function createMenuItems({
  openAddEntry,
  showAddEntryPanel,
  openMenu,
  toggleSubMenu,
  lockVault,
  triggerSecurityAction,
  startChange,
  openTimeoutSettings,
  displayPanel,
  showThemePicker,
  showLockBgPicker,
  showBackupModal,
  openImportPicker,
  openRecoveryCode,
  startBatchUpdate,
  setDisplayPanel,
  setShowThemePicker,
  setShowLockBgPicker,
  setShowBackupModal,
  toggleNerdPanel,
}) {
  return [
    { label: '➕ Add Entry',              action: () => { openAddEntry(); showAddEntryPanel = true; } },
    { label: '⚙️ Settings',              action: () => { openMenu(); toggleSubMenu('settings'); } },
    { label: '👮🏻‍♂️ Security',             action: () => { openMenu(); toggleSubMenu('security'); } },
    { label: '🔒 Lock Vault',             action: () => lockVault() },
    { label: '📱 2FA Settings',           action: () => triggerSecurityAction('totp_settings') },
    { label: '🔎 Security Report',        action: () => triggerSecurityAction('security_report') },
    { label: '🦾 Change Password',        action: () => startChange() },
    { label: '🫙 Silo Mode',             action: () => triggerSecurityAction('in_secure') },
    { label: '⏱️ Timeout',               action: () => openTimeoutSettings() },
    { label: '🎨 Themes',                 action: () => setShowThemePicker(true) },
    { label: '🏞️ Lock Screen Background', action: () => setShowLockBgPicker(true) },
    { label: '☁️ Backup Settings',        action: () => { setShowBackupModal(true); } },
    { label: '⤵️ Import',                action: () => openImportPicker() },
    { label: '🪣 Batch Update Icons',     action: () => startBatchUpdate() },
    { label: '🧠 Nerd Stats', action: () => toggleNerdPanel() },
    { label: '🔑 Recovery Code', action: () => openRecoveryCode() },
  ];
}